build: false
clone_depth: 5
platform:
  - x86
  - x64
clone_folder: c:\projects\composer

cache:
  - c:\tools\php -> appveyor.yml

init:
  - SET PATH=c:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)

install:
  - IF EXIST c:\tools\php (SET PHP=0)
  - IF %PHP%==1 cinst -y php --params "/InstallDir:c:\tools\php"
  - cd c:\tools\php
  - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
  - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
  - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - cd c:\projects\composer
  - composer install --prefer-dist --no-progress

test_script:
  - cd c:\projects\composer
  - vendor/bin/phpunit --colors=always
